version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - "./backend/src:/usr/app/src"
    links:
      - mongo
    depends_on:
      - mongo
    command: yarn dev:server

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/usr/app/src"
    command: yarn start

  mongo:
    image: "mongo"
    volumes:
      - "./data/db:/data/db"
    ports:
      - "27017:27017"
